#!/bin/bash
# AnonymousDelivers file uploader

function upload_stdin {
	curl -s -L -F "userfile=@-;filename=$1" -F "private=$PRIVATE" $URL | head -n 1 | awk '{print $2}'
}

function upload_file {
	curl -s -L -F "userfile=@$1;filename=$1" -F "private=$PRIVATE" $URL | head -n 1 | awk '{print $2}'
}

URL="http://anonymousdelivers.us/upload"
PRIVATE=0
FAILURES=0

if [ "$1" = "-p" ]; then
	PRIVATE=1
	shift
fi

if [ ! -n "$1" ]; then
	echo "AnonymousDelivers.us"
	echo "Usage:"
	echo "    upload files: $(basename $0) [-p] file [file ...]"
	echo "    upload from stdin: $(basename $0) [-p] -f [name]"
	echo "    upload screenshot: $(basename $0) [-p] -s"
	echo "Options:"
	echo "    -p      Make private link"
	exit 10
fi

if [ "$1" = "-f" ]; then
	shift
	if [ "$1" = "-p" ]; then
		PRIVATE=1
		shift
	fi
	if [ -n "$1" ]
	then
		RESULT=$(upload_stdin "$1")
	else
		RESULT=$(upload_stdin stdout_`whoami`.txt)
	fi
	if [[ "$RESULT" =~ ^http:// ]]; then
			echo "$RESULT"
	else
			echo "fail"
			let "FAILURES+=1"
	fi
elif [ "$1" = "-s" ]; then
	shift
	if [ "$1" = "-p" ]; then
		PRIVATE=1
		shift
	fi
	file=`date +'/tmp/%d-%m-%Y %H-%M.png'`
	screencapture "$file" 2> /dev/null || scrot -s "$file"
	RESULT=$(upload_file "$file")
	if [[ "$RESULT" =~ ^http:// ]]; then
			echo "$RESULT"
	else
			echo "fail"
			let "FAILURES+=1"
	fi
	rm "$file"
else
	for file in "$@"
	do
		RESULT=$(upload_file "$file")
		if [[ "$RESULT" =~ ^http:// ]]; then
				echo "$file: $RESULT"
		else
				echo "$file: fail"
				let "FAILURES+=1"
		fi
	done
fi

exit $FAILURES
