#!/bin/bash

set -xue

V="6.10.2"
CHECKSUM="9b897dd6604d50ae5fff25fd14b1c4035462d0598735799e0cfb4f17cb6e0d19"
NODEJS_PREFIX="${HOME}/.nodejs-root"
SRCCACHE="${HOME}/.cache/nodejs-src"

SRCFNAME="node-v${V}.tar.gz"
URL="http://nodejs.org/dist/v${V}/${SRCFNAME}"

mkdir -p "$SRCCACHE"
if [ ! -f "${SRCCACHE}/${SRCFNAME}" ]; then
    wget -O "${SRCCACHE}/${SRCFNAME}" "$URL"
fi
echo "${CHECKSUM}  ${SRCCACHE}/${SRCFNAME}" | sha256sum -c

T=$(mktemp -d)

SRCDIR="${T}/src"
mkdir "$SRCDIR"
tar -C "$SRCDIR" -xf "${SRCCACHE}/${SRCFNAME}"

# Patch to compile with GCC 4.7
cd "${SRCDIR}" && patch -u -p1 < $HOME/.bin/nodejs.patch

cd "${SRCDIR}/node-v${V}" && ./configure --prefix="$NODEJS_PREFIX"
make -C "${SRCDIR}/node-v${V}" -j 4
make -C "${SRCDIR}/node-v${V}" install

rm -rf "$T"
