#!/bin/bash

# sudo apt-get install libtool-bin libtool automake git

set -xue

PB_ROOT="${HOME}/.protobuf-root"
PB_SRC="${HOME}/src/github.com/google/protobuf"
LUA_PB="${HOME}/src/github.com/indygreg/lua-protobuf"
GRPC_SRC="${HOME}/src/github.com/grpc/grpc"

# protobuf itself
if [ ! -d "$PB_SRC" ]; then
    mkdir -p "$PB_SRC"
    git clone https://github.com/google/protobuf "$PB_SRC"
fi
cd "$PB_SRC"
./autogen.sh
T=$(mktemp -d)
cd "$T" && "${PB_SRC}/configure" --prefix "$PB_ROOT"
make -j 4
make install
rm -r "$T"

# gRPC

if [ ! -d "$GRPC_SRC" ]; then
    git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc "$GRPC_SRC"
fi
cd "$GRPC_SRC"
git submodule update --init
T=$(mktemp -d)
# https://github.com/grpc/grpc/issues/10948
sed 's@.emplace("", true)@[""] = true@' -i src/cpp/server/health/default_health_check_service.cc
# W_SHADOW= b/c https://github.com/grpc/grpc/issues/10945
make -j 4 prefix="$PB_ROOT" W_SHADOW=
make install prefix="$PB_ROOT"
rm -r "$T"

# Go (needs ./install-go)
go get \
    google.golang.org/grpc \
    github.com/golang/protobuf/{proto,protoc-gen-go}

# Python
cd "${PB_SRC}/python"
python setup.py install --user

# Lua
if [ ! -d "$LUA_PB" ]; then
    mkdir -p "$LUA_PB"
    git clone https://github.com/indygreg/lua-protobuf "$LUA_PB"
fi
cd "$LUA_PB"
python setup.py install --user
# https://github.com/indygreg/lua-protobuf#missing-plugin_pb2-python-module
# Put this file to ~/.local/bin/plugin_pb2.py
T=$(mktemp -d)
protoc \
    -I"${PB_SRC}/src" \
    --python_out "$T" \
    "${PB_SRC}/src/google/protobuf/compiler/plugin.proto"
cp "${T}/google/protobuf/compiler/plugin_pb2.py" "$HOME/.local/bin"
rm -r "$T"
sed -i 's/google.protobuf.compiler.plugin_pb2/plugin_pb2/' \
    $(grep -l google.protobuf.compiler.plugin_pb2 -r $HOME/.local/lib)
# Test
HELLOWORLD_OUT=$(mktemp -d)
mkdir -p "$HELLOWORLD_OUT"
HELLOWORLD="${GOPATH}/src/google.golang.org/grpc/examples/helloworld/helloworld"
protoc \
    -I "$HELLOWORLD" \
    --lua_out "$HELLOWORLD_OUT" \
    "${HELLOWORLD}/helloworld.proto"
rm -r "$HELLOWORLD_OUT"
