#!/bin/bash

set -xue

V="3.0"
CHECKSUM="c89f76229e6cf8c56df6b74aef9ed0bd"
SRCCACHE="${HOME}/.cache/astyle-src"

SRCFNAME="astyle_${V}_linux.tar.gz"
URL="https://sourceforge.net/projects/astyle/files/astyle/astyle%203.0/${SRCFNAME}/download"

mkdir -p "$SRCCACHE"
if [ ! -f "${SRCCACHE}/${SRCFNAME}" ]; then
    wget -O "${SRCCACHE}/${SRCFNAME}" "$URL"
fi
echo "${CHECKSUM}  ${SRCCACHE}/${SRCFNAME}" | md5sum -c

T=$(mktemp -d)

SRCDIR="${T}/src"
mkdir "$SRCDIR"
tar -C "$SRCDIR" -xf "${SRCCACHE}/${SRCFNAME}"

cd "$SRCDIR/astyle/build/gcc"
make
cp bin/astyle "${HOME}/.bin"

rm -r "$T"
