#!/bin/bash

audio=$1
if [[ $audio == "" ]] ; then
    audio=0
fi

channels=$2
if [[ $channels == "" ]] ; then
    channels=2
fi

out=`mktemp $HOME/webcam-XXXXXXXXXX.avi`

ffmpeg -sameq -f video4linux2 -r 25 -s 640x480 -i /dev/video0 \
    -f alsa -ac $channels -i hw:$audio,0 -acodec mp2 -y $out

echo $out

